version: '3.4'

services:
  tiger.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIGERWEBAPI_PACKAGE_WATCHER=Thread
    ports:
      - "5000:80"
    volumes:
      - "/Users/kevin/DockerData/Packages:/app/Packages"